openapi: 3.0.0
info:
  title: petstore-api
  description: this api will consist details of different animals, kind, size and age
  version: "1.0.0"
servers:
  - url: https://petstore-example.com
tags:
  - name: size
  - name: id
  - name: age
paths:
  /id:
    get:
      summary: Get animal by ID
      description: Retrieve details of an animal by its ID
      tags:
        - id
      responses:
        '200':
          description: Successful response
        '404':
          description: Animal not found