name: CI/CD Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}  # Use a matrix strategy for different OS runners

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]  # List of OS runners to use

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Installing Dependencies
      run: |
        if [ ${{ matrix.os }} == 'windows-latest' ]; then
          # Use Windows-specific commands for setup
          # For example, you can install Windows PowerShell modules
        else
          # Use Linux-specific commands for setup
          # For example, you can use 'apt-get' to install dependencies
          Install-Module -Name Az -Force -AllowClobber
          Import-Module -Name Az
          Uninstall-AzureRm
          Install-Module -Name powershell-yaml -Force
          Import-Module -Name powershell-yaml

    - name: Lint OpenAPI (Spectral)
      if: startsWith(matrix.os, 'ubuntu')  # Only run on Linux
      uses: morigs/lint-api-docs-action@v1.0.0

    - name: Publish OpenAPI Spec to Postman
      if: startsWith(matrix.os, 'ubuntu')  # Only run on Linux
      uses: aanimesh23/openapi-publish-action@v1
      with:
        collectionName: MyCollection
        workspaceName: Api Lifecycle
        postmanApiKey: PMAK-652680f168a9e70afa583323-d8369fb2eb8babf7734a63193df75fd0d4
        openApiSpec: openapi.yaml

    - name: Run PowerShell script
      if: startsWith(matrix.os, 'windows')  # Only run on Windows
      run: |
        # Run your Windows-specific PowerShell script
        .\everesrapidynamic.ps1
