name: CI/CD Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16

    - name: Installing Dependencies
      run: |
        Install-Module -Name Az -Force -AllowClobber
        Import-Module -Name Az
        Uninstall-AzureRm
        Install-Module -Name powershell-yaml -Force
        Import-Module -Name powershell-yaml
        npm install -g @stoplight/spectral
        npm install -g openapi-to-postmanv2
      
    - name: API Specification Validation (Spectral)
      run: |
        # Install Spectral
        spectral lint --ruleset .api/spectral.yml openapi.yaml

    - name: Generate Postman Collection
      run: |
        openapi2postmanv2 -s openapi.yaml -o .api/collection.json -p -O requestParametersResolution=Example,optimizeConversion=false,stackLimit=50

    - name: Run PowerShell script
      run: |
        # Run your PowerShell script
        .\everesrapidynamic.ps1
