name: CI/CD Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-2019

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Run Spectral Validation
      run: |
        # Download the Windows version of Spectral
        iwr https://github.com/stoplightio/spectral/releases/latest/download/spectral.exe -OutFile spectral.exe
        .\spectral.exe lint openapi.yaml --ruleset https://raw.githubusercontent.com/stoplightio/spectral/master/rulesets/oas2-schema.yml
      working-directory: ${{ github.workspace }}

    - name: Installing Dependencies
      run: |
        Install-Module -Name Az -Force -AllowClobber
        Import-Module -Name Az
        Uninstall-AzureRm
        Install-Module -Name powershell-yaml -Force
        Import-Module -Name powershell-yaml

    - name: Run PowerShell script
      run: |
        # Run your PowerShell script
        .\everesrapidynamic.ps1
