name: CI/CD Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16

    - name: Installing Dependencies
      run: |
        Install-Module -Name Az -Force -AllowClobber
        Import-Module -Name Az
        Uninstall-AzureRm
        Install-Module -Name powershell-yaml -Force
        Import-Module -Name powershell-yaml

    - name: openapi-to-postman-action
      uses: fluximus-prime/openapi-to-postman-action@v1.0.1
      with:
        postmanApiKey: PMAK-652680f168a9e70afa583323-d8369fb2eb8babf7734a63193df75fd0d4
        openApiSpec: openapi.yml
      
    - name: Lint OpenAPI (Spectral)
      run: |
        # Install Spectral
        npm install -g @stoplight/spectral
        spectral lint --ruleset .api/spectral.yml openapi.yaml

    - name: Run PowerShell script
      run: |
        # Run your PowerShell script
        .\everesrapidynamic.ps1
