name: CI/CD Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-2019

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Installing Dependencies
      run: |
        Install-Module -Name Az -Force -AllowClobber
        Import-Module -Name Az
        Uninstall-AzureRm
        Install-Module -Name powershell-yaml -Force
        Import-Module -Name powershell-yaml

    - name: Run spectral lint
      uses: ahmetgeymen/spectral-lint-action@v1.0
      with:
        file_path: openapi.yml

    - name: Publish OpenAPI Spec to Postman
      uses: aanimesh23/openapi-publish-action@v1
      with:
        collectionName: MyCollection
        workspaceName: Api Lifecycle
        postmanApiKey: PMAK-652680f168a9e70afa583323-d8369fb2eb8babf7734a63193df75fd0d4
        openApiSpec: openapi.yaml

    - name: Run PowerShell script
      run: |
        # Run your PowerShell script
        .\everesrapidynamic.ps1
