name: CI/CD Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-2019

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - run: |
        # Run your PowerShell script
        .\everesrapidynamic.ps1
    - name: Generate Postman Collection
      uses: fluximus-prime/openapi-to-postman-action@v1.0.1
      with:
        openapi_url: openapi.yaml
        output_file: postman-collection.json
