name: CI/CD Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-2019

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - run: |
        # Run your PowerShell script
        .\everesrapidynamic.ps1
