name: CI/CD Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16

    - name: Installing Dependencies
      run: |
        Install-Module -Name Az -Force -AllowClobber
        Import-Module -Name Az
        Uninstall-AzureRm
        Install-Module -Name powershell-yaml -Force
        Import-Module -Name powershell-yaml

      
    - name: Lint OpenAPI (Spectral)
      run: |
        # Install Spectral
        npm install -g @stoplight/spectral
        spectral lint --ruleset .api/spectral.yml openapi.yaml

    - name: Install api-spec-converter
      run: |
        npm install -g api-spec-converter
        api-spec-converter --from=openapi_3 --to=swagger_2 --syntax=json --order=openapi openapi.yaml > swagger.json
      

    - name: Run PowerShell script
      run: |
        # Run your PowerShell script
        .\everesrapidynamic.ps1
