name: CI/CD Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-2019

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Az module
      run: Install-Module -Name Az -Force -AllowClobber

    - name: Uninstall AzureRm module
      run: |
        Uninstall-AzureRm

    - name: Import Az Module
      run: |
        Import-Module -Name Az
    - run: |
        # Run your PowerShell script
        .\everesrapidynamic.ps1
