name: CI/CD Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Installing Dependencies
      run: |
        if ($env:RUNNER_OS -eq "Windows") {
          # Use Windows-specific commands for setup
        } else {
          # Use Linux-specific commands for setup
          Install-Module -Name Az -Force -AllowClobber
          Import-Module -Name Az
          Uninstall-AzureRm
          Install-Module -Name powershell-yaml -Force
          Import-Module -Name powershell-yaml
        }

    - name: Generate Postman Collection
      if: ${{ runner.os }} == 'ubuntu-latest'
      uses: fluximus-prime/openapi-to-postman-action@v1.0.1
      with:
        postmanApiKey: ${{ secrets.POSTMAN_API_KEY }}
        openApiSpec: openapi.yaml

    - name: Lint OpenAPI (Spectral)
      if: ${{ runner.os }} == 'ubuntu-latest'
      uses: morigs/lint-api-docs-action@v1.0.0

    - name: Publish OpenAPI Spec to Postman
      if: ${{ runner.os }} == 'ubuntu-latest'
      uses: aanimesh23/openapi-publish-action@v1
      with:
        collectionName: MyCollection
        workspaceName: MyWorkspace
        postmanApiKey: ${{ secrets.POSTMAN_API_KEY }}
        openApiSpec: path/to/openapi.yaml

    - name: Run PowerShell script
      if: ${{ runner.os }} == 'windows-latest'
      run: |
        # Run your Windows-specific PowerShell script
        .\everesrapidynamic.ps1
